version: '3.3'

services:
  phpapache:
    #image: titangene/php-apache-mysql:v1.0
    build: ./php
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - mysql
    volumes:
      - ./html:/var/www/html
  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      #MYSQL_DATABASE: testdb
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306